### ISSUE TITLE
Unresolved Reference Error:

### ISSUE THREAD

**Issue by BharathRaoSS** [Evin1-/Kotlin-MVP-Dagger2-RxJava-Retrofit#2]
When I downloaded it as .Zip file (without git VCS) DaggerApplicationComponent.Builder() shows unresolved reference error in android studio. There is no  DaggerApplicationComponent under the package named "di".

**Comment by Evin1-** [comment]
Thanks @BharathRaoSS, that's the expected behavior of any project with Dagger. Since they use compilation time generated code, you need to build your Android Studio project first, before the DaggerApplicationComponent is created for you.
